### ISSUE TITLE
Investigate/Fix use with FireFox

### ISSUE THREAD

**Issue by Sean-Der** [pions/turn#19]
Continuing #16 it was reported that FireFox currently doesn't work, investigate and fix

**Comment by Sean-Der** [comment]
Hey @winds2016

Would you mind trying 1.0.3 I published a new release that fixes FireFox, I tested with 60.0

thanks for all the help!

**Comment by winds2016** [comment]
@Sean-Der 
OK, I will test it

**Comment by winds2016** [comment]
@Sean-Der 
I use two firefox client, call and talk is ok. 
But when i hold the talk,and hold time is long than 20 seconds,firefox will say ICE failed, next i cancel the hold ,talk has no audio again.
Now simple turn have not show any info(1.0.3).

Maybe it is firefox's issue? chrome is ok.

**Comment by Sean-Der** [comment]
Nice, glad it is working! 

If you don't do the hold are the two FireFoxes able to work for more then twenty seconds (just doing hold is the only thing that breaks it) That is an odd one with the hold, will look into that.

I am going to start a contributors section, would you mind if put you down as a thank you? I really appreciate all the testing you have done.

**Comment by winds2016** [comment]
Ok ,thank you too
